#/APPNICENAME=pyLoad
#/APPDESCRIPTION=Python Download Manager alternative to JDownloader
services:
  pyload:
    container_name: pyload
    image: writl/pyload:latest
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${DOWNLOADSDIR}:/opt/pyload/Downloads
      - ${DOCKERCONFDIR}/pyload:/opt/pyload/pyload-config
